let mockApartments = [
  {
    id: 1,
    street: "101 Rimrock",
    unit: "9A",
    city: "San Diego",
    state: "CA",
    square_footage: 500,
    price: "1800",
    bedrooms: 2,
    bathrooms: 2.0,
    pets: "yes!",
    image: "https://mcdn.wallpapersafari.com/medium/71/85/shnKtz.png",
    user_id: 1,
  },
  {
    id: 2,
    street: "720 Second Avenue",
    unit: "508",
    city: "San Diego",
    state: "CA",
    square_footage: 700,
    price: "2500",
    bedrooms: 2,
    bathrooms: 2.0,
    pets: "yes!",
    image:
      "https://mcdn.wallpapersafari.com/medium/48/81/7bFhy5.jpg",
    user_id: 1,
  },
  {
    id: 3,
    street: "415 Rainbow Street",
    unit: "3B",
    city: "San Diego",
    state: "CA",
    square_footage: 400,
    price: "2000",
    bedrooms: 1,
    bathrooms: 2.0,
    pets: "small pets okay",
    image:
      "https://mcdn.wallpapersafari.com/medium/68/19/8SzYOP.png",
    user_id: 2,
  },
  {
    id: 4,
    street: "415 Rainbow Street",
    unit: "3B",
    city: "San Diego",
    state: "CA",
    square_footage: 400,
    price: "2000",
    bedrooms: 1,
    bathrooms: 2.0,
    pets: "small pets okay",
    image:
      "https://mcdn.wallpapersafari.com/medium/46/92/BsIE23.jpg",
    user_id: 2,
  },
  {
    id: 5,
    street: "415 Rainbow Street",
    unit: "3B",
    city: "San Diego",
    state: "CA",
    square_footage: 400,
    price: "2000",
    bedrooms: 1,
    bathrooms: 2.0,
    pets: "small pets okay",
    image:
      "https://mcdn.wallpapersafari.com/medium/3/31/qMY9iV.jpg",
    user_id: 2,
  },
  {
  id: 5,
  street: "415 Rainbow Street",
  unit: "3B",
  city: "San Diego",
  state: "CA",
  square_footage: 400,
  price: "2000",
  bedrooms: 1,
  bathrooms: 2.0,
  pets: "small pets okay",
  image:
    "https://mcdn.wallpapersafari.com/medium/6/20/7Ze8D9.jpg",
  user_id: 2,
},
];

export default mockApartments;
